### PR TITLE
Update composer.json so can be installed

### PR DESCRIPTION
**Pull request by jackmcpickle**
use https://composer.github.io/installers/ to manage installation

### CODE REVIEW

**Comment by jackmcpickle** [comment]
preferably the folder structure would change - but will leave that up to you.

**Comment by johndwells** [comment]
Hey @jackmcpickle thanks for submitting this - I'm keen to incorporate it. I'd rather not change the folder structure, though I'm curious exactly how people would get around it. Can you offer advice or point me to a resource that I could then base some simple documentation on?

**Comment by jackmcpickle** [comment]
Hi @johndwells, 

to get around the structure issues composer has a `post-install-cmd` you can add which runs after the `composer install` command. 

See a sample of our composer so we can use mimimee in our craft apps.

```
{
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/sealink/craft.minimee.git"
    },
  ],
  "require": {
    "johndwells/craft.minimee": "v0.9.7"
  },
  "scripts": {
    "post-install-cmd": [
      "/bin/bash -c 'pushd craft/plugins && test -d minimee/minimee && mv minimee/minimee/* minimee && popd'"
    ]
  }
}
```
once this is merged you will need to submit to [packagist](https://getcomposer.org/doc/02-libraries.md#publishing-to-packagist) and then I would be able to remove the line referencing my fork.

**Comment by johndwells** [comment]
Super Jack, I really appreciate the explanation.

On 23 March 2016 at 13:31, Jack McNicol <notifications@github.com> wrote:

> Hi @johndwells <https://github.com/johndwells>,
>
> to get around the structure issues composer has a post-install-cmd you
> can add which runs after the composer install command.
>
> See a sample of our composer so we can use mimimee in our craft apps.
>
> {
>   "repositories": [
>     {
>       "type": "vcs",
>       "url": "https://github.com/sealink/craft.minimee.git"
>     },
>   ],
>   "require": {
>     "johndwells/craft.minimee": "v0.9.7"
>   },
>   "scripts": {
>     "post-install-cmd": [
>       "/bin/bash -c 'pushd craft/plugins && test -d minimee/minimee && mv minimee/minimee/* minimee && popd'"
>     ]
>   }
> }
>
> once this is merged you will need to submit to packagist
> <https://getcomposer.org/doc/02-libraries.md#publishing-to-packagist> and
> then I would be able to remove the line referencing my fork.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/johndwells/craft.minimee/pull/21#issuecomment-200344087>
>



-- 
Pura Vida
John D Wells
http://www.johndwells.com

**Comment by jackmcpickle** [comment]
Hi @johndwells any update on this?

Also the registration of the plugin with https://packagist.org/ would be a big plus too. 
You would also need to setup a webhook to enable auto updating.

This enables on `$ composer install` to be able to read from the registered package list rather than pull and fetch every branch/tag and then read the composer.json file for each. Much faster.

Thanks

**Comment by plankguy** [comment]
+1 would love to be able to manage w/ composer!

**Pull request merged**
