### PR TITLE
Include inline assets

### PR DESCRIPTION
**Pull request by Joe1992w**
Get any inline styles or scripts and append them to the returned HTML.

### CODE REVIEW

**Comment by johndwells** [comment]
Hi Joe,

Thanks for the contribution, unfortunately I'm not inclined to accept this.  Reason being, any inline cache can't be "busted" in the way that a file's contents can be, which is a rather core feature in Minimee.  When someone is looking for inline minification, I happily recommend Andrew Khalwat's Minify plugin: https://github.com/nystudio107/minify

Cheers,
John

**Comment by adamdburton** [comment]
Hi John,

Some plugins use the [includeJs](https://craftcms.com/docs/templating/includejs), [includeCss](https://craftcms.com/docs/templating/includecss) and [includeHiResCss](https://craftcms.com/docs/templating/includehirescss) functions to add their inline js/css to the footer of the page. Unfortunately your filter strips these out as they don't match your regex patterns for asset files.

What Joe has implemented allows these inline assets to still be on the page whilst caching/minifying the file-based assets, as they are added after the script/link tag. Cache-busting the inline assets isn't required as they are in the page response instead of another the cached js/css file.

**Comment by johndwells** [comment]
Can you provide a code sample where minimee is interfering with those twig functions?

I see the larger point but still want to be clear about usage. 

Cheers
John

**Comment by adamdburton** [comment]
An example of the includeJs function being used is at https://github.com/objectivehtml/Google-Maps-for-Craft/blob/master/services/GoogleMaps_TemplatesService.php#L63

With the following in a template:

`{{ craft.googleMaps.map({
    id: 'map', 
    width: '400px', 
    height: '300px',
    center: 'The Florida Keys',
    options: {
        disableDoubleClickZoom: true,
        maxZoom: 10,
        zoomControlOptions: {
            position: 'google.maps.ControlPosition.LEFT_CENTER',
            style: 'google.maps.ZoomControlStyle.LARGE'
        }
    }
}) }}`

And with `{{ getFootHtml() | minimee }}` before `</body>`, the inline js added by the maps plugin is not output as minimee is stripping it from the content.

**Comment by adamdburton** [comment]
I do realise that your README states:

> Note that any inline CSS or JS passed via {% includeJs %}, {% includeCss %} and{% includeHiResCss %} is currently not supported.

This is a fix for that issue as these inline assets should not be cached anyway.

**Comment by johndwells** [comment]
Thanks - I did wonder if this might have to do with google maps (having used smart map myself).

This code change is potentially destructive however (far as I can tell). If the pre filtered markup includes a mix of external, inline, more external and more inline code, the result would be reordered code. All of the minified code first, all inline second. 

I do get what is being attempted here, I've looked at it before. Unfortunately I still don't think this is the right solution.

**Comment by adamdburton** [comment]
Please see https://github.com/pixelandtonic/Craft-Release/blob/86ec2b157a0d2f5cb1337a5ac8d74a3fb5067f2b/app/services/TemplatesService.php#L719. All external files are output first, followed by all inline.

I don't mean to keep going backwards and forwards on this, but currently your filter is more destructive than with this fix as it removes content from page output.

**Comment by johndwells** [comment]
Good to know that getFootHtml() does that, but adding this feature opens up
the situation where someone else might come along and throw a mix of raw
tags, not with getFootHtml(), and come complaining to me that I've
reordered their code.

I do appreciate what is trying to be accomplished here...

Perhaps if it were added as a configuration that was off by default, like
`preserveInlineJs` and `preserveInlineCss`, which if turned on did just
that, but with the explicit & documented note that by doing so, final
output *may* be reordered.

What do you think about that?


Sent from my iPhone

On 6 Mar 2017, at 12:11, Adam Burton <notifications@github.com> wrote:

Please see https://github.com/pixelandtonic/Craft-Release/blob/
86ec2b157a0d2f5cb1337a5ac8d74a3fb5067f2b/app/services/
TemplatesService.php#L719. All external files are output first, followed by
all inline.

I don't mean to keep going backwards and forwards on this, but currently
your filter is more destructive than with this fix as it removes content
from page output.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/johndwells/craft.minimee/pull/29#issuecomment-284379830>,
or mute the thread

**Pull request closed without merging**
